import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataPath = join(__dirname, 'src', 'data', 'escape-rooms.json');
const rooms = JSON.parse(readFileSync(dataPath, 'utf8'));

const webs = {
  'er-001': 'https://www.odiseaescape.com',
  'er-002': 'https://www.elementsescaperoom.com',
  'er-003': 'https://lainiciativa.es',
  'er-004': 'https://www.elementsescaperoom.com',
  'er-005': 'https://neverlandescape.com',
  'er-006': 'https://quimeraescape.com',
  'er-007': 'https://mataro.cubickroomescape.es',
  'er-008': 'https://www.odiseaescape.com',
  'er-009': 'https://playescaperoom.es',
  'er-010': 'https://mataro.cubickroomescape.es',
  'er-011': 'https://mataro.cubickroomescape.es',
  'er-012': 'https://www.reddopamine.com',
  'er-013': 'https://bajosegunda.com',
  'er-014': 'https://thecityescaperoom.com',
  'er-015': 'https://cindyescapebox.com',
  'er-016': 'https://www.xcaperoombcn.com',
  'er-017': 'https://www.elementsescaperoom.com',
  'er-018': 'https://terrorstories.com/barcelona',
  'er-019': 'https://residentriddle.com',
  'er-020': 'https://www.odiseaescape.com',
  'er-021': 'https://fugitivosroomescape.com',
  'er-022': 'https://www.elementsescaperoom.com',
  'er-023': '',
  'er-024': 'https://cindyescapebox.com',
  'er-025': 'https://www.elementsescaperoom.com',
  'er-026': 'https://www.keyplay.es',
  'er-027': 'https://malumescaperoom.com',
  'er-028': 'https://rowkaescaperoom.com',
  'er-029': 'https://outlineescaperoom.es',
  'er-030': 'https://residentriddle.com',
  'er-031': 'https://www.elementsescaperoom.com',
  'er-032': 'https://www.reddopamine.com',
  'er-033': 'https://lock-clock.com',
  'er-034': 'https://playescaperoom.es',
  'er-035': 'https://playescaperoom.es',
  'er-036': 'https://horrorbox.es',
  'er-037': 'https://therombocode.es/barcelona/',
  'er-038': 'https://horrorbox.es',
  'er-039': 'https://thehive.barcelona',
  'er-040': 'https://quimeraescape.com',
  'er-041': 'https://www.escapebarcelona.com',
  'er-042': 'https://maximumescape.com',
  'er-043': 'https://openmindroomescape.es',
  'er-044': 'https://therombocode.es/barcelona/',
  'er-045': 'https://unrealroomescape.es',
  'er-046': 'https://www.xcaperoombcn.com',
  'er-047': 'https://prison-experience.com',
  'er-048': 'https://lock-clock.com',
  'er-049': 'https://escapehunt.com/es/location/barcelona/',
  'er-050': 'https://mysteryescape.es',
  'er-051': 'https://mysteryescape.es',
  'er-052': 'https://www.picaderomotel.com',
  'er-053': 'https://www.lostesorosdelahistoria.com',
  'er-054': 'https://enigmalegacy.es/barcelona/',
  'er-055': 'https://www.enigmik.com',
  'er-056': 'https://fugitivosroomescape.com',
  'er-057': 'https://escapehunt.com/es/location/barcelona/',
  'er-058': 'https://bcn.aventurico.com',
  'er-059': 'https://www.xcaperoombcn.com',
  'er-060': 'https://maximumescape.com',
  'er-061': 'https://horrorbox.es',
  'er-062': 'https://bcn.aventurico.com',
  'er-063': 'https://goldenpop.es',
  'er-064': 'https://www.escapebarcelona.com',
  'er-065': 'https://mysteryescape.es',
  'er-066': 'https://thehive.barcelona',
  'er-067': 'https://prison-experience.com',
  'er-068': 'https://fugitivosroomescape.com',
  'er-069': 'https://fugitivosroomescape.com',
  'er-070': 'https://fugitivosroomescape.com',
  'er-071': 'https://roomwhitechapel.com',
  'er-072': 'https://www.emotionescape.com',
  'er-073': 'https://prison-experience.com',
  'er-074': 'https://therombocode.es/barcelona/',
  'er-075': 'https://therombocode.es/barcelona/',
  'er-076': 'https://escapehunt.com/es/location/barcelona/',
  'er-077': 'https://escapehunt.com/es/location/barcelona/',
  'er-078': 'https://lock-clock.com',
  'er-079': 'https://openmindroomescape.es',
  'er-080': 'https://horrorbox.es',
  'er-081': 'https://www.picaderomotel.com',
  'er-082': 'https://www.kadabraescape.com',
  'er-083': 'https://maximumescape.com',
  'er-084': 'https://psicopatasanonimos.com',
  'er-085': 'https://lock-clock.com',
  'er-086': 'https://maximumescape.com',
  'er-087': 'https://quimeraescape.com',
  'er-088': 'https://maximumescape.com',
  'er-089': 'https://unrealroomescape.es',
  'er-090': 'https://thehive.barcelona',
  'er-091': 'https://therombocode.es/barcelona/',
  'er-092': 'https://maximumescape.com',
  'er-093': 'https://maximumescape.com',
};

let updated = 0;
for (const room of rooms) {
  room.web = webs[room.id] ?? '';
  if (room.web) updated++;
}

writeFileSync(dataPath, JSON.stringify(rooms, null, 2), 'utf8');
console.log(`Fet! ${updated}/93 rooms amb web.`);
